### ISSUE TITLE
Domains Endpoints

### ISSUE THREAD

**Issue by almeiphi** [diconium/ethereal-pulse#28]
Draft: Implementation of `/domains` endpoints operations and update the swagger docs if necessary.

**Comment by ivanLOliveira** [comment]
## Description

Implement a new route in the server (NestJS) to manage email domains. This route will handle CRUD operations for email domains, serving as a list of `from` emails for sending emails from the application.

## Acceptance Criteria

- [ ] `/api/email/domains` endpoint is successfully implemented and tested.
- [ ] Controller methods handle CRUD operations for email domains (GET all, GET by ID, POST, PUT, DELETE).
- [ ] The service layer effectively encapsulates email domain-related business logic.
- [ ] MongoDB integration stores and retrieves email domains correctly.
- [ ] Error handling is in place to manage exceptions and edge cases gracefully.
- [ ] Authentication mechanisms secure the `/api/email/domains` endpoint.
- [ ] API documentation is updated with details of the `/api/email/domains` endpoint and includes comprehensive examples.

## Additional Context

- Email domains serve as a predefined list of `from` emails for sending emails from the application.
- Ensure the route follows RESTful principles and adheres to best practices for API design.
- Consider scalability and performance optimizations for handling a potentially large number of email domains.
