### ISSUE TITLE
Web Application Azure Deployment

### ISSUE THREAD

**Issue by almeiphi** [diconium/ethereal-pulse#49]
## Description

Setup deployment for the web app project on Azure. This includes configuring the infrastructure, setting up CI/CD pipelines.

## Acceptance Criteria

- [ ] Azure resources are created and configured correctly.
- [ ] CI/CD pipeline is set up and working with GitHub Actions.
- [ ] Web app is deployed
- [ ] Environment variables are configured and managed securely.
- [ ] Monitoring and logging are set up for the deployed services.

**Comment by FernandoDiconium** [comment]
Github action for build and deploy is done, working on documentation.
