### ISSUE TITLE
Deploy DB

### ISSUE THREAD

**Issue by ivanLOliveira** [diconium/ethereal-pulse#76]
# Deploy MongoDB into Azure

## Description

We need to deploy MongoDB into Azure to ensure our application has a scalable and reliable database infrastructure. This involves setting up an Azure Cosmos DB instance with MongoDB API, configuring necessary settings, and ensuring connectivity with our application.

## Additional Context

- Utilize Azure Cosmos DB with MongoDB API for compatibility and scalability.
- Ensure the database is secure, performant, and reliable.
- Follow best practices for cloud-based MongoDB deployments.

## Labels

`database`, `azure`, `mongodb`, `deployment`

## Acceptance Criteria

- [ ] Azure Cosmos DB account with MongoDB API is created and configured.
- [ ] Databases and collections are set up with appropriate settings.
- [ ] Authentication and authorization are set up, including access keys.
- [ ] Documentation is provided for setup, configuration, scaling, and connectivity.

**Comment by FernandoDiconium** [comment]
Working on it

**Comment by FernandoDiconium** [comment]
Done
