### ISSUE TITLE
Groups endpoints

### ISSUE THREAD

**Issue by almeiphi** [diconium/ethereal-pulse#81]
## Description

Implement a new route in the server (NestJS) to manage email groups. This route will handle CRUD operations for groups of emails, allowing organizations and properties that aid in selecting groups for sending emails.

## Acceptance Criteria

- [ ] `/api/groups` endpoint is successfully implemented and tested.
- [ ] Controller methods handle CRUD operations for email groups (GET all, GET by ID, POST, PUT, DELETE).
- [ ] Service layer encapsulates email group-related business logic effectively.
- [ ] MongoDB integration stores and retrieves email groups correctly.
- [ ] Comparison properties for email groups aid in selecting groups for email distribution.
- [ ] Error handling is in place to manage exceptions and edge cases gracefully.
- [ ] Authentication mechanisms secure the `/api/groups` endpoint.
- [ ] API documentation is updated with details of the `/api/groups` endpoint and includes comprehensive examples.

## Additional Context

- Email groups allow organization and categorization of email addresses.
- Properties associated with groups aid in selecting the appropriate group(s) for email distribution.
- Ensure the route follows RESTful principles and adheres to best practices for API design.
- Consider scalability and performance optimizations for handling a potentially large number of email groups.

**Comment by ivanLOliveira** [comment]
# Implement Group Route in Server (NestJS)

## Description

Implement a new route in the server (NestJS) to manage email groups. This route will handle CRUD operations for groups of emails, allowing organizations and properties that aid in selecting groups for sending emails.

## Acceptance Criteria

- [ ] `/api/groups` endpoint is successfully implemented and tested.
- [ ] Controller methods handle CRUD operations for email groups (GET all, GET by ID, POST, PUT, DELETE).
- [ ] Service layer encapsulates email group-related business logic effectively.
- [ ] MongoDB integration stores and retrieves email groups correctly.
- [ ] Comparison properties for email groups aid in selecting groups for email distribution.
- [ ] Error handling is in place to manage exceptions and edge cases gracefully.
- [ ] Authentication mechanisms secure the `/api/groups` endpoint.
- [ ] API documentation is updated with details of the `/api/groups` endpoint and includes comprehensive examples.

## Additional Context

- Email groups allow organization and categorization of email addresses.
- Properties associated with groups aid in selecting the appropriate group(s) for email distribution.
- Ensure the route follows RESTful principles and adheres to best practices for API design.
- Consider scalability and performance optimizations for handling a potentially large number of email groups.
