### ISSUE TITLE
Build SDK package local

### ISSUE THREAD

**Issue by almeiphi** [diconium/ethereal-pulse#82]
## Description

Set up the SDK package to facilitate integration with external projects and ensure its functionality meets requirements when used outside the current development environment.

## Acceptance Criteria

- [ ] SDK package is successfully set up locally
- [ ] Integration testing confirms SDK functionality in an external project environment.
- [ ] SDK documentation is updated with clear installation, usage, and integration instructions.
- [ ] Compatibility issues or bugs encountered during testing are identified and resolved if not outside of scope.
- [ ] SDK performance meets expected standards without significant issues or bottlenecks.

## Additional Context

- The SDK aims to simplify integration with external applications for email functionality.
- Ensure compatibility with different Node.js versions and environments where the SDK might be deployed.
- Consider security best practices and data privacy concerns when handling email operations.

**Comment by ivanLOliveira** [comment]
## Description

Set up the SDK package to facilitate integration with external projects and ensure its functionality meets requirements when used outside the current development environment.


## Acceptance Criteria

- [ ] SDK package is successfully set up locally
- [ ] Integration testing confirms SDK functionality in an external project environment.
- [ ] SDK documentation is updated with clear installation, usage, and integration instructions.
- [ ] Compatibility issues or bugs encountered during testing are identified and resolved if not outside of scope.
- [ ] SDK performance meets expected standards without significant issues or bottlenecks.



## Additional Context

- The SDK aims to simplify integration with external applications for email functionality.
- Ensure compatibility with different Node.js versions and environments where the SDK might be deployed.
- Consider security best practices and data privacy concerns when handling email operations.
